### ISSUE TITLE
Exclusion lists inconsistency 

### ISSUE THREAD

**Issue by Rosentreter** [LethalMaus/StreamingYorkie#1] opened 2019-03-18 07:50 UTC
When I exclude a user in 'Following' I expect that in 'F4F' the user to also be excluded.
However, when excluded in 'Following' it is nowhere to be seen in 'F4F', the numbers are in total one less for each excluded in 'Following' or 'Followers'.

**Comment by LethalMaus** [comment] 2019-03-18 07:56
I was able to reproduce this issue as well. This will be within the next release.
Thank you for the info

**Comment by LethalMaus** [comment] 2019-03-18 10:21
As discussed, when excluding in 'Followers' or 'Following' this will not reflect in list views e.g. in 'F4F'.
This is due to the complication & disadvantages with Users who are in all 3. Having single lists offers more customization within the list view.
It will however still be excluded from AutoFollow regardless which exclusion list it belongs to.
This will be explained better in the guide. The bug for the inconsistency has been found & fixed. It will be included in the next update this week

**Closed as completed by LethalMaus** 2019-03-18 10:21 UTC
